<!-- Explain the difference between a Python list and a NumPy array in terms of 
memory usage and performance. 
Then, write a program that creates both and performs element-wise 
multiplication. -->
| Feature                 | Python List                                       | NumPy Array                                        |
| ----------------------- | ------------------------------------------------- | -------------------------------------------------- |
| Memory Usage            | Stores elements as separate objects (more memory) | Stores elements in contiguous memory (less memory) |
| Data Type               | Can store mixed data types                        | Stores same data type only                         |
| Speed                   | Slower for numerical operations                   | Faster for numerical operations                    |
| Element-wise Operations | Not directly supported                            | Directly supported                                 |


In [1]:
# # What is broadcasting in NumPy? 
# # Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain 
# # how NumPy applies the operation internally.  
# Broadcasting in NumPy is a technique that allows arrays of different shapes to perform arithmetic operations together.

# Instead of manually resizing arrays, NumPy automatically expands (broadcasts) the smaller array to match the shape of the larger array — without actually copying data.
import numpy as np

# 3x3 array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 1D array
B = np.array([10, 20, 30])

# Broadcasting addition
result = A + B

print("Matrix A:\n", A)
print("Array B:\n", B)
print("Result:\n", result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array B:
 [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [2]:
# #  What are missing values in Pandas and how are they represented? 
# # Create a DataFrame with missing values and write code to: 
# # • Detect missing values 
# # • Replace them with the column mean 
# # Explain each step. 

# In pandas, missing values are data entries that are empty or undefined.

# They usually occur when:

# Data is incomplete

# Some values are not recorded

# Errors happen during data collection
import pandas as pd
import numpy as np

# Create DataFrame with missing values
data = {
    "Math": [80, 90, np.nan, 70, 85],
    "Science": [75, np.nan, 65, 80, 90],
    "English": [np.nan, 88, 92, 85, 79]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)


Original DataFrame:
   Math  Science  English
0  80.0     75.0      NaN
1  90.0      NaN     88.0
2   NaN     65.0     92.0
3  70.0     80.0     85.0
4  85.0     90.0     79.0


In [3]:
# #  Explain boolean indexing in NumPy or Pandas. 
# # Create a DataFrame with at least 5 columns and filter rows based on two conditions 
# # using logical operators. Explain how filtering works internally.

# Boolean indexing is a method used in NumPy and pandas to filter data based on conditions.

# It works by:

# Creating a Boolean mask (True/False values).

# Selecting only those rows where the condition is True.
import pandas as pd

# Create DataFrame with 5 columns
data = {
    "Name": ["Aman", "Riya", "Karan", "Sneha", "Rahul"],
    "Age": [21, 19, 23, 20, 22],
    "Math": [85, 92, 78, 88, 95],
    "Science": [90, 85, 70, 95, 80],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


Original DataFrame:
     Name  Age  Math  Science     City
0   Aman   21    85       90    Delhi
1   Riya   19    92       85   Mumbai
2  Karan   23    78       70    Delhi
3  Sneha   20    88       95  Chennai
4  Rahul   22    95       80   Mumbai


In [4]:
# # What is the purpose of the groupby() function in Pandas? 
# # Create a DataFrame with categorical data (e.g., department & salary) and calculate 
# # the average salary per department using groupby(). Explain the output. 

# In pandas, the groupby() function is used to:

# Split → Apply → Combine

# Split the data into groups based on a column (usually categorical data).

# Apply an aggregate function (like mean, sum, count).

# Combine the results into a new summarized DataFrame.

# It is mainly used for:

# Data summarization

# Aggregation

# Statistical analysis
import pandas as pd

# Create DataFrame
data = {
    "Employee": ["Aman", "Riya", "Karan", "Sneha", "Rahul", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Salary": [60000, 45000, 70000, 50000, 48000, 52000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


Original DataFrame:
   Employee Department  Salary
0     Aman         IT   60000
1     Riya         HR   45000
2    Karan         IT   70000
3    Sneha    Finance   50000
4    Rahul         HR   48000
5     Neha    Finance   52000
